attributes = [
    {'name': 'color', 'terms': [
        {'name': 'red', 'term_id': 1},
        {'name': 'green', 'term_id': 2},
        {'name': "yellow", 'term_id': 3},
        {'name': "black", 'term_id': 4},
        {'name': "white", 'term_id': 5},
        {'name': "pink", 'term_id': 12},
        {'name': "gray", 'term_id': 13},
        {'name': "beige", 'term_id': 14},
        {'name': "orange", 'term_id': 15},
        {'name': "navy_blue", 'term_id': 16},
        {'name': "purple", 'term_id': 17},
        {'name': "gold", 'term_id': 18},
        {'name': "silver", 'term_id': 19},
        {'name': "multicolor", 'term_id': 20},
        {'name': "other", 'term_id': 22},
        {'name': "blue", 'term_id': 32},
        {'name': "brown", 'term_id': 33},
    ]},
    {'name': 'size', 'terms': [
        {'name': 'xs', 'term_id': 6},
        {'name': 's', 'term_id': 7},
        {'name': "m", 'term_id': 8},
        {'name': "l", 'term_id': 9},
        {'name': 'xl', 'term_id': 10},
        {'name': 'xxl', 'term_id': 11},
        {'name': 'universal', 'term_id': 12},
    ]},
]

categories = [
    {"name": 'Damskie', 'category_id': 4},
    {"name": 'Sukienki i kombinezony', 'category_id': 2},
    {"name": 'Bluzki i koszule', 'category_id': 9},
    {"name": 'Swetry i bluzy', 'category_id': 8},
    {"name": 'T-shirty', 'category_id': 10},
    {"name": 'Marynarki i kurtki', 'category_id': 7},
    {"name": 'Płaszcze', 'category_id': 6},
    {"name": 'Spodnie', 'category_id': 11},
    {"name": 'Spódnice', 'category_id': 13},
    {"name": 'Kimona', 'category_id': 41},
    {"name": 'Zestawy', 'category_id': 40},
]