# Generated by Django 4.2.3 on 2023-08-02 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordpressCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.DecimalField(decimal_places=0, max_digits=10)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='WordpressProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.DecimalField(decimal_places=0, max_digits=10)),
                ('slug', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('categories', models.ManyToManyField(related_name='products', to='wordpress.wordpresscategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordpressProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.DecimalField(decimal_places=0, max_digits=10)),
                ('name', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('colour', models.CharField(max_length=60)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='wordpress.wordpressproduct')),
            ],
        ),
        migrations.CreateModel(
            name='WordpressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wordpress.wordpressproduct')),
            ],
        ),
    ]
