# Generated by Django 4.2.3 on 2023-08-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0002_wordpresscategory_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpressattribute',
            name='sku',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
