# Generated by Django 4.2.3 on 2023-08-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0003_wordpressattribute_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordpressterms',
            old_name='option',
            new_name='name',
        ),
    ]
