# Generated by Django 4.2.3 on 2023-08-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0004_rename_option_wordpressterms_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpressproduct',
            name='attributes',
            field=models.ManyToManyField(related_name='products', to='wordpress.wordpressattribute'),
        ),
    ]
