# Generated by Django 4.2.3 on 2023-08-14 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0005_wordpressproduct_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordpressProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.ManyToManyField(related_name='variations', to='wordpress.wordpressattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='wordpress.wordpressproduct')),
            ],
        ),
    ]
