# Generated by Django 4.2.3 on 2023-08-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0006_wordpressproductvariation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordpressattribute',
            old_name='sku',
            new_name='attribute_id',
        ),
        migrations.RenameField(
            model_name='wordpresscategory',
            old_name='sku',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='wordpressproduct',
            old_name='sku',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='wordpressproductvariation',
            name='variation_id',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
