# Generated by Django 4.2.3 on 2023-08-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0007_rename_sku_wordpressattribute_attribute_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordpressproduct',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='wordpressproductvariation',
            name='attributes',
        ),
        migrations.AddField(
            model_name='wordpressproduct',
            name='terms',
            field=models.ManyToManyField(related_name='products', to='wordpress.wordpressterms'),
        ),
        migrations.AddField(
            model_name='wordpressproductvariation',
            name='terms',
            field=models.ManyToManyField(related_name='variations', to='wordpress.wordpressterms'),
        ),
    ]
