# Generated by Django 4.2.3 on 2023-08-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0008_remove_wordpressproduct_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpressproduct',
            name='json_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WordpressProductVariation',
        ),
    ]
