# Generated by Django 4.2.3 on 2023-08-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0010_remove_wordpressproduct_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordpressproduct',
            name='name',
        ),
    ]
