# Generated by Django 4.2.3 on 2023-08-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0011_remove_wordpressproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpressproduct',
            name='variations_json_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
