# Generated by Django 4.2.3 on 2023-09-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0012_wordpressproduct_variations_json_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordpressproduct',
            options={'ordering': ['product_id']},
        ),
    ]
