# Generated by Django 4.2.3 on 2023-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0013_alter_wordpressproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpressproduct',
            name='variations_json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
