# Generated by Django 4.2.3 on 2023-08-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wordpress', '0003_wordpressattribute_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorismaAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('wordpress_attribute', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='storisma_attributes', to='wordpress.wordpressattribute')),
            ],
        ),
        migrations.CreateModel(
            name='StorismaTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('name', models.CharField(max_length=60)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='storisma.storismaattribute')),
                ('wordpress_term', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='storisma_terms', to='wordpress.wordpressterms')),
            ],
        ),
        migrations.CreateModel(
            name='StorismaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('name', models.CharField(max_length=60)),
                ('wordpress_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='storisma_categories', to='wordpress.wordpresscategory')),
            ],
        ),
    ]
