# Generated by Django 4.2.3 on 2023-08-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0003_wordpressattribute_sku'),
        ('storisma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storismacategory',
            name='wordpress_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='storisma_categories', to='wordpress.wordpresscategory'),
        ),
    ]
