# Generated by Django 4.2.3 on 2023-08-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0005_wordpressproduct_attributes'),
        ('storisma', '0003_alter_storismaattribute_wordpress_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storismacategory',
            name='wordpress_category',
        ),
        migrations.AddField(
            model_name='storismacategory',
            name='wordpress_category',
            field=models.ManyToManyField(related_name='storisma_categories', to='wordpress.wordpresscategory'),
        ),
    ]
