# Generated by Django 4.2.3 on 2023-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storisma', '0006_storismaproduct_wordpress_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='storismaproductvariation',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
