# Generated by Django 4.2.3 on 2023-09-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storisma', '0008_storismaproductvariation_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='storismaproductvariation',
            name='attributes',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
