# Generated by Django 4.2.3 on 2023-09-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storisma', '0009_storismaproductvariation_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storismaproductvariation',
            name='attributes',
        ),
        migrations.CreateModel(
            name='StorismaProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='storisma.storismaattribute')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='storisma.storismaterm')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='storisma.storismaproductvariation')),
            ],
        ),
    ]
